### ISSUE TITLE
Change expect.all to accept (Boolean | Expectation)*

### ISSUE THREAD

**Issue by stacycurl** [disneystreaming/weaver-test#131]
At present it can only be used to combine simple expectations

**Comment by Baccata** [comment]
That's gonna be a no-go, sorry. The reason is that the implementation of `all` is macro-based and relies on boolean expressions being inlined in the varargs. Having the "all" method take an heterogenous list of values would require fiddling a lot more with macros and I'm not comfortable with that idea (moreover the macros are defined in an [upstream library](https://github.com/eed3si9n/expecty))

If you need to combine a `List[Expectations]`, you can use foldMap (`Expectations` is monoidal). Weaver provides an [alias](https://github.com/disneystreaming/weaver-test/blob/master/modules/core/src/weaver/Expectations.scala#L119-L120) out of the box for it. You can build a varargs-based version of it in userland in a couple lines of code

**Comment by stacycurl** [comment]
Well, how about another method that takes a var args of Expectation ?

**Comment by Baccata** [comment]
> Well, how about another method that takes a var args of Expectation ?

 PRs are welcome 😄

**Comment by Baccata** [comment]
Won't fix for reason stated above : Expectations is monoidal and cats provides a number of combinators to collapse collections of monoids
