### ISSUE TITLE
specs2 integration - using `and` on `beSome`'s `ValueCheck` leads to failure

### ISSUE THREAD

**Issue by LLCampos** [disneystreaming/weaver-test#280]
WeaverVersion = 0.7.0
Specs2Version = 4.10.6

The following passes:

```scala
import org.specs2.mutable._

class MySuite extends Specification {
  "my test" >> {
    Some(1) must beSome((i: Int) => {
      (true must beTrue) and (true must beTrue)
    })
  }
}
```

But the equivalent in weaver doesn't.

```scala
import weaver._
import weaver.specs2compat.IOMatchers

object MySuite2 extends SimpleIOSuite with IOMatchers {
  test("my test") {
    Some(1) must beSome((i: Int) => {
      (true must beTrue) and (true must beTrue)
    })
  }
}
```

```
MySuite2
- my test 19ms
*************FAILURES**************
MySuite2
- my test 19ms
  Some(1) is Some but 1: java.lang.Integer != MySuite2$$$Lambda$175/352076319@76ab2cc5: MySuite2$$$Lambda$175/352076319 (../experiment-with-stuff-scala/src/test/scala/weaver.scala:6)

Execution took 19ms
1 tests, 1 failed
```

**Comment by LLCampos** [comment]
I'm looking into this ^^

**Comment by LLCampos** [comment]
`beSome` expects a function that returns a `MatchResult`, but when we use `and` we force specs2's `MatchResult` into weaver's` Expectations`. specs2 has its own `and` but it's overloaded by weaver's.

This means that if, inside `beSome` we use any function that returns `Expectations` (e.g., weaver's `and`, `or`, `xor`) the test will fail.

I added some failing tests [here](https://github.com/disneystreaming/weaver-test/pull/281).

**Comment by Baccata** [comment]
Ergh that's a pickle. To solve this in userland, rather than using `IOMatchers`, you could override the `test` method (which provides a few alternative shapes by means of a PartiallyApplied construct) and add some additional shapes that'd take the same thing but `MatchResult` instead, and would delegate to the original methods after having transformed the MatchResult to Expectations. 

Since IOMatchers is meant to be mixed in with other traits, I don't think we can use that technique upstream ... I guess we could have a `spec(...)` method that'd do the same thing as `test` though, with matchers instead of expectations. 

What do you think ?

**Comment by LLCampos** [comment]
@Baccata, I would say that having a different a different test method (`spec(...)`) is undesirable from a user experience point of view. :confused: Although it might be the best option if no alternative. 

Anyway, I had a go at an different solution [here](https://github.com/disneystreaming/weaver-test/pull/281), which I'm not totally sure about.

**Comment by Baccata** [comment]
Closing as specs2 support has been removed.
