### ISSUE TITLE
GlobalResource's do not get released while using forkedJvm in SBT 

### ISSUE THREAD

**Issue by aevanszen** [disneystreaming/weaver-test#473]
When using multiple `GlobalResource's` in a `forked` JVM in SBT, not all the resources are released, i.e. release in `Resource.make(acquire)(release)` never gets invoked.

Frequently only the first GlobalResource is released gracefully.

I suspect this is because Weaver attempts to close the resources, and in parallel, sends the test outcome to SBT. Once SBT gets the test outcome, it terminates the forked JVM before all resources have the release task executed on them.

If not using a forked jvm you can see the `Resource's` are released after the tests have completed in SBT.

I would expect the behavior to be all Resource's are released before signaling to SBT the tests/task is complete.

If we use a non global shared resource, resource's are released as expected.

I have a sample project at https://github.com/ssahayam-zd/weaver-resource-cleanup which demonstrates this.

**Comment by lukestephenson** [comment]
Looked a bit more at the weaver code base.  I suspect the cause of the bug is that the weaver framework keeps "sbt tasks" active via a poll loop.
https://github.com/disneystreaming/weaver-test/blob/3f833b8ed30ce8be7e1953f8d8e9b2f994e78071/modules/framework/src-jvm/SbtTask.scala#L37

That SuiteFinished is triggered here https://github.com/disneystreaming/weaver-test/blob/3f833b8ed30ce8be7e1953f8d8e9b2f994e78071/modules/framework/src-jvm/RunnerCompat.scala#L198

But that is triggered within the resource.use block. https://github.com/disneystreaming/weaver-test/blob/3f833b8ed30ce8be7e1953f8d8e9b2f994e78071/modules/framework/src-jvm/RunnerCompat.scala#L158

And as far as I can tell, the framework creates "SBT Tasks" which it waits on, and there is also a wait on the resources to be created initially, but there is no wait for resources to be cleaned up here. https://github.com/disneystreaming/weaver-test/blob/3f833b8ed30ce8be7e1953f8d8e9b2f994e78071/modules/framework/src-jvm/RunnerCompat.scala#L111-L117

Potentially the solution is to create an additional SBT task to represent resource cleanup which only completes when all resources have been released.  Keen to get feedback on this idea from someone more familiar with weaver (assuming I've even understood what the cause of the problem is).

**Comment by Baccata** [comment]
@lukestephenson that's a pretty good analysis 👍  

So far, we've avoided the "additional SBT task" solution, because of how some build tools discard tasks if they don't map to a given suite class. To circumvent that annoyance, what we do is have the suite that completes last "own" the logging of the [final summary](https://github.com/disneystreaming/weaver-test/blob/3f833b8ed30ce8be7e1953f8d8e9b2f994e78071/modules/framework/src-jvm/SbtTask.scala#L38-L40), by using an atomic boolean for the task to self-identify as the "last running one". 

I think the best solution would be to add an additional java semaphore to pass to the constructor of `SbtTask`, which would try to acquire it when in that same `stillRunning.decrementAndGet == 0` conditional. 

The java semaphore would be initialised with 0 permit, and passed all the way to  [resourceMap](https://github.com/disneystreaming/weaver-test/blob/3f833b8ed30ce8be7e1953f8d8e9b2f994e78071/modules/framework/src-jvm/RunnerCompat.scala#L167-L169), which would use it to construct a `Resource[IO, Unit]` that'd be responsible for the release of a single permit upon finalisation. This resource would be composed on the left of the rest, in order for the release to occur after all other finalisers have run. 

If someone could give this a go, that'd be great. Otherwise I can allocate time next week.
