### ISSUE TITLE
log4cats integration?

### ISSUE THREAD

**Issue by timbertson** [disneystreaming/weaver-test#497]
I haven't used weaver's Log class much, because I'm mostly just using crufty old slf4j - it currently seems designed just for logging within tests, as I don't want my production code to depend on weaver. But I do have dependencies which use log4cats.

I don't know if you'd be happy to adopt the log4cat interface wholesale (it'd have to be a new major version), but in the short term it'd be possible to bridge via the following implicit:

```scala
package weaver

import org.typelevel.log4cats.{Logger => CatsLogger}
import weaver.{Log => WeaverLog}

object LoggerImplicits {
  implicit def loggerForWeaver[F[_]](implicit wl: WeaverLog[F]) = new CatsLogger[F] {
    override def error(t: Throwable)(message: => String): F[Unit] = wl.error(msg = message, cause = t)

    override def warn(t: Throwable)(message: =>String): F[Unit] = wl.warn(msg = message, cause = t)

    override def info(t: Throwable)(message: =>String): F[Unit] = wl.info(msg = message, cause = t)

    override def debug(t: Throwable)(message: =>String): F[Unit] = wl.debug(msg = message, cause = t)

    override def trace(t: Throwable)(message: =>String): F[Unit] = wl.debug(msg = message, cause = t)

    override def error(message: =>String): F[Unit] = wl.error(message)

    override def warn(message: =>String): F[Unit] = wl.warn(message)

    override def info(message: =>String): F[Unit] = wl.info(message)

    override def debug(message: =>String): F[Unit] = wl.debug(message)

    override def trace(message: =>String): F[Unit] = wl.debug(message)
  }
}
```

The `trace` is a bit of a wrinkle, since weaver doesn't have trace level. The implementation is very boring, but it'd be good to put in weaver proper so that users don't all have to write it. `log4cats-core` only depends on `cats-core`, so it shouldn't add much dependency weight.

With this in scope, you can use `loggedTest { implicit log => ... }` and the implementation can freely call anything taking an implicit `Logger[F]`.

**Comment by Baccata** [comment]
Hey @timbertson, I'm sorry for replying only now. 

> I don't know if you'd be happy to adopt the log4cat interface wholesale. 

Unfortunately, logs4cats doesn't quite cut it for our usecase, mostly because of [this](https://github.com/disneystreaming/weaver-test/blob/master/modules/core/src/weaver/Log.scala#L30) implicit parameter, which tracks the source location of the log, and that's useful information for us internally. 

This implicit source location is fed to the call sites implicitly. That is using the same mechanism that lets most test frameworks in the Scala ecosystem expose the location of the assertion(s) that failed during a test. 

Scala 2 doesn't allow to abstract implicit parameters away, which means that whatever interface we provide has to expose this implicit parameter in the methods. We might revisit if/when we ever discard Scala 2, but that is years from now.

So unfortunately, you'll have to stick with your bridge for the time being.

**Comment by timbertson** [comment]
Sorry for the slow response. That makes sense, in that you can't use log4cats directly. Would you be open to exposing a `weaver-log4cats` module which contains this implicit? I know it's not that big, but it seems silly to copy-paste into each project. I could of course host it as a third-party module, it might just be nice to have it in weaver itself for consistent versioning & discoverability.

**Comment by Baccata** [comment]
> Would you be open to exposing a weaver-log4cats module which contains this implicit? 

I'm sorry to say I'm not open to it : looking back, having the integrations directly embedded in the same codebase has been a maintenance burden/hassle, even for things seemingly simple/trivial and I don't want to add any more. I'd even go as far as saying that I'd keen to split weaver into smaller repos.

**Comment by timbertson** [comment]
Fair call, I can always stand up my own library if it annoys me enough ;)
