### ISSUE TITLE
The `Expectations` are in a `Kleisli`

### ISSUE THREAD

**Issue by inanme** [disneystreaming/weaver-test#529]
I'd like to return `Expectations` defined in `Kleisli` data type to define my tests. Maybe the following spec/suite:
```
object SomeTest extends IOSuite {
  override type Res = Int
  override def sharedResource: Resource[IO, Int] = Resource.pure(1)

  test("fds") { int =>
    val m = Kleisli[IO, Int, Expectations](int => IO(assert(int == 1)))
    m.run(int)
  }
}
```
could look like this:
```
object SomeTest extends IOSuite {
  override type Res = Int
  override def sharedResource: Resource[IO, Res] = Resource.pure(1)

test("fds") {
    Kleisli[IO, Int, Expectations](int => IO(assert(int == 1)))
  }
}
```

Quick/Naive thinking could suggest adding this overload to achieve above.

```
class PartiallyAppliedTest(name : TestName) {
  def apply(run: => Kleisli[F, Res, Expectations]) : Unit = registerTest(name)(res => Test(name.name, run.apply(res)))
    ...
}
```

The point of issue is to collect feedback on this.

**Comment by Baccata** [comment]
Hey, sorry for not having replied before, for some reason I missed it. 

Anyhow, you can add a method the `PartiallyAppliedTest`, in userland, via an extension class. You probably won't be able to overload the `apply` with a by-name parameter, because type-erasure, but you could either make it a by-value parameter, or add a method named something else than "apply". In that case, the UX would look like : 

```scala 
test("foo").kleisli {
 ....
} 
```

If you can find a name other than `kleisli` that would be fitting, I would consider accepting a PR that'd add this (as a first-class, non-extension method)

**Comment by inanme** [comment]
np, I will see what I can do.
