### ISSUE TITLE
Support cross-suite resource sharing

### ISSUE THREAD

**Issue by pshirshov** [disneystreaming/weaver-test#7]
Hi,

Right now it's not possible to share one resource between several test suites. In many cases it may be a very annoying limitation.  [`distage-testkit`](https://izumi.7mind.io/distage/distage-testkit.html#testkit) collects global knowledge and builds a global test plan ahead of time which makes cross-suite shared resources possible. In case you wish we would be happy to share our experience and design ideas.

**Comment by Baccata** [comment]
Hi, thanks for opening this issue. 

We are interested in providing this feature for the medium term and already have some ideas. We're aware of distage (and the izumi-reflect library that was donated to the zio org), but we're wary about not adding more dependencies to the core than we already have. 

We haven't really decided on a design just yet, but having a deeper look at how distage works has been on my todo-list for a while 😄

**Comment by pshirshov** [comment]
> but having a deeper look at how distage works has been on my todo-list for a while 😄

We may setup a call and talk about these thingies if you wish :)

**Comment by Baccata** [comment]
> By the way, in case you use zio you already have  

Yup, we're aware, however the core module doesn't have a dependency on zio and we intend to keep it that way.  

> "Test Server Protocol" 

That sounds interesting, I'd be keen to hear your ideas, if there's some reasonable tweaks we can make to open that a possibly, I'd definitely consider them. I'm a bit busy this week and the next, but hit me up on gitter or by email and we can have a call.

**Comment by dimitarg** [comment]
Pasting something here that I drafted for our internal documentation at work

One workaround is to declare a parent suite as an object, child suites as traits, and mix in the child suites in the parent suite.
This effectively creates just one suite but lets you split that across separate files.

To put this in code, given

```scala
final case class FooResource()
final case class BarResource(value: Int)
final case class Resources(fooResource: FooResource, barResource: BarResource)
```

, declare "child" suite traits

```scala
import weaver.IOSuite

trait ChildSuite extends IOSuite { self: AllSuites.type =>
  test("accessing shared resource") { r =>
    expect(r.barResource.value == 42)
  }
}
```

and a "parent" suite instantiating the children

```scala
import cats.effect.{IO, Resource}
import weaver.IOSuite

object AllSuites extends IOSuite
  with ChildSuite {
  override type Res = Resources

  override def sharedResource: Resource[IO, Resources] = for {
    foo <- Resource.pure(FooResource())
    bar <- Resource.pure(BarResource(42))
    _ <- Resource.liftF(IO(println("initialised resources")))
  } yield Resources(foo, bar)
}
```

## Disadvantages

- This effectively creates just one suite. Consequences of this
    - All test names will be prefixed with `AllSuites` instead of the child name
    - all the child suites and the parent suite will share the same implicit scope, which in certain
    cases will be unwanted
    - The type of the suite resource will be the same across all suites. There is no way to say that
    a child suite is only interested in a subset of the resources, i.e. `type Res = FooResource`
- Resource sharing depends on subtyping and mixins, which is non-idiomatic for a functional codebase

**Comment by dimitarg** [comment]
> We haven't really decided on a design just yet

To me it seems the fundamental issue right now is that `test()` does not return a description but performs a side effect. I can see why this was done, it makes API simpler and makes you get away with one less concept to learn as a user, and aids in automatic test discovery.

That being said, I have a gut feeling suites should be (possibly tree-like) data structures that can be transformed composed etc, because right now resource sharing is achieved via mutable state in the suite instance, which will in my opinion make it extremely hard to achieve cross-suite resource sharing, at least without very intricate and brittle machinery

I am writing all this also in the context of 
>The type of the suite resource will be the same across all suites. There is no way to say that
a child suite is only interested in a subset of the resources, i.e. type Res = FooResource**

I think this is a very important feature - having a "lens" over a shared resource so you can view only what applies to you in a given suite.

**Comment by Baccata** [comment]
Hi @dimitarg, thanks for the input. 

### Regarding the current design decisions 

Let me start by giving some context : weaver implements [sbt's test interface](https://github.com/sbt/test-interface), which largely limits what can be done in terms of pure functional programs : it implicitly considers each suite to be a separate "end of the world" and expects them to run in isolation. It is the semantics of that particular interface that prevent tree like structures of suites, if you want to benefit from features such as autocompletion in sbt when calling "testOnly", or bloop when using "-o". 

We are already violating the semantics of the interface to allow for reporting the results at the end of the run, across test suites. This works with sbt / bloop when testing JVM code, but doesn't work with ScalaJS because of how SBT (and other build tools) relies on a serialisation mechanism to communicate information between the JVM runtime and the javascript one. We do support ScalaJS and have made the decision to simply report each suite's failures separately in that context. 

A decision could be made to violate the semantics further and weave all suites into a single IO before running them (on JVM only), but we aren't comfortable with that level of violation because : 

1. it'd make JVM and JS implementations diverge further from each other 
2. it would disrespect userland settings such as asking SBT to run suites in sequence or parallel

### Side note regarding the "imperative registration of tests" with suites

The kind of suite we currently advertise in documentation does indeed register tests imperatively to stick with UX that frameworks such as minitest/utest provide. This is a subjective choice that caters primarily to our teams at DSS, our teams are happy with the UX and we're not really interested in maintaining complex DSLs à la scalatest. 

**HOWEVER** weaver detects any suite extending [this trait](https://github.com/disneystreaming/weaver-test/blob/master/modules/core/src/weaver/suites.scala#L22) which doesn't contain any kind of imperative semantics, meaning you could come up with some kind of pattern that would be closer to @kubukoz's [flawless](https://github.com/kubukoz/flawless). If you did and PR'd it in, we'd obviously consider merging it in the codebase to cater to people who are more comfortable with the total absence of imperative patterns. The two could coexist. 

### Back to the problem at hand 

So, as said earlier, the principal hurdle is trying to solve this problem whilst minimising the amount of violation to sbt's test interfaces semantics. Additional constraint are : 

1. We want to retain source compatibility as much as possible. We have teams that use internally and my greatest responsibility is to keep them happy, which means I don't want to break their code. 
2. I don't want to change the [core](https://github.com/disneystreaming/weaver-test/tree/master/modules/core) module because this problem is very much induced by the test interface (which is implemented in (https://github.com/disneystreaming/weaver-test/tree/master/modules/framework) 

**I am currently implementing a solution with these constraints in mind**. It might not be the perfect solution (the perfect solution would probably have a "Test server protocol" like @pshirshov mentions, that would cater to the concern of safe resource sharing, and have build tools use that instead of sbt's interface), but it will be "not too magic" 

> having a "lens" over a shared resource so you can view only what applies to you in a given suite.

My solution will not require suites to be aware of the globality of shared resource, if that reassures you.

**Comment by dimitarg** [comment]
Thanks for the detailed answer! I will write back once I ingest it. Haven't yet familiarised myself with the internals properly, I guess I was mostly looking at `MutableFSuite` and you can tell. 
Also wanted to say - great work on this library! Just ported some code at work and it's a strict improvement in a lot of ways. Specifically
>not really interested in maintaining complex DSLs à la scalatest

the fact the API surface is so small makes it a joy to work with.

**Comment by Baccata** [comment]
@dimitarg thanks for the kind words 😄

**Comment by dimitarg** [comment]
Right, so I reread parts of your exposition and looked and played around with the code. Thanks for the pointers. So this works (i.e. gets picked up by sbt and executed)

```
import cats.effect.IO
import weaver.{PureIOSuite, TestOutcome}

object BlahSuite extends PureIOSuite {
  override def spec(args: List[String]): fs2.Stream[IO, TestOutcome] = fs2.Stream.eval(
    pureTest("k") {
      expect(1 == 1)
    }
  )
}
```

, and does not require exposing non-RT API. Equivalently something can be built on top of `EffectSuite` which builds up a program tree with the resource sharing properties I am looking for; of course since I will (the user will) be building up the actual tree there will be no auto-discoverability (beyond the auto discovery of that suite implementation and its `spec` method), but that fits my requirements exactly. Further, even though this can and should be PRed to the project, it appears this can currently be done in user land with 0 changes to `weaver-test`. 

So I got thrown off thinking `weaver-test` is at odds with what I'm trying to do, but that's just the `MutableFSuite` implementation.

**Comment by dimitarg** [comment]
@pshirshov OP, sorry I piggybacked and spun this in another direction, it's the same requirement overall so I felt it's not useful to create a separate issue.

**Comment by dimitarg** [comment]
FWIW this achieves my usecase, in case it helps anyone:

https://github.com/dimitarg/weaver-test-extra/blob/574c01ba97f00af46f1604075f149428fa75da3c/src/test/scala/com/dimitarg/example/ExampleResSuite.scala

The "library" implementation is fairly small and simple, I will probably publish it once it's polished.

**Comment by Baccata** [comment]
@dimitarg, I should have made it more explicit in this ticket but we've added support for cross-suite resource sharing that's a bit more FP idiomatic, see [here](https://disneystreaming.github.io/weaver-test/docs/global_resources)
