### ISSUE TITLE
Integrate with scalacheck-effect 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/weaver-test#79]
https://github.com/typelevel/scalacheck-effect

This has existed for only a month but respects Scalacheck idioms much better than our hand-rolled  integration that didn't account for the "Prop" since they were creating a synchronous boundary.

**Comment by Baccata** [comment]
Won't fix : scalacheck-effect is constrained to sequential execution of property checks. 

In contrast, weaver's scalacheck integration relies on fs2 for the stream of seeds, which allows to use the `parEvalMap` combinator, allowing for parallel execution of properties.

**Comment by armanbilge** [comment]
> Won't fix : scalacheck-effect is constrained to sequential execution of property checks.

So that makes sense and all, but it kind of misses the point of scalacheck effect. Which is the ability to do `forAll` with assertions in an effect. Can weaver do that?

**Comment by armanbilge** [comment]
> Which is the ability to do `forAll` with assertions in an effect. Can weaver do that?

Yes, seems it can. So then a scalacheck-effect integration is not necessary, because it would be pointless: Weaver offers the same functionality.

Sorry if this is all obvious, it just wasn't clear to me :) would be worth putting this information somewhere under "scalacheck effect" for folks who are looking to migrate.

**Comment by Baccata** [comment]
You mean in the docs ? Sure
